services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    WebSlinger\MailerFactory\MailerFactory:
        arguments:
            $testEmail: '%webslinger.mailer_factory.test_email%'
            $apiEnv: '%webslinger.mailer_factory.api_env%'
            $uploadDirectory: '%webslinger.mailer_factory.upload_directory%'
            $subjectPrefix: '%webslinger.mailer_factory.subject_prefix%'
            $enableErrorLogging: '%webslinger.mailer_factory.enable_error_logging%'
        public: true

    WebSlinger\MailerFactory\Command\InstallCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
        tags:
            - { name: 'console.command' }
